import { priced } from './pricing.js';

/**
 * Demonstration dataset used for Supabase seeding and offline fallback.
 * Mirrors the 8 NFT records shown on the home page:
 * 5 unpaid, 1 paid, 1 appeal_pending, 1 voided.
 */
export const DEMO_VIOLATIONS = [
  // UNPAID
  priced({
    code: 'SC-7F3A1B8C4D2E',
    refId: 'SC-2026-051744',
    kind: 'speeding',
    status: 'unpaid',
    plate: 'SK 8822 MT',
    vehicleMake: 'BMW 318d',
    carColor: 'black',
    dateTime: '2026-05-14T13:37:00',
    street: { mk: 'Бул. Борис Трајковски', en: 'Boris Trajkovski Blvd.', sr: 'Булевар Борис Трајковски' },
    city: { mk: 'Скопје', en: 'Skopje', sr: 'Скопље' },
    coordinates: { lat: 41.98022, lng: 21.44419 },
    speedRecorded: 91,
    speedLimit: 50,
    cameraId: 'CAM-SK-052',
    issuedAt: '2026-05-14T13:58:00',
    baseFineEUR: 300,
    drivingBan: {
      mk: 'Забрана за управување од 3 до 12 месеци.',
      en: 'Driving ban from 3 to 12 months.',
      sr: 'Забрана управљања од 3 до 12 месеци.',
    },
    legalNote: {
      mk: 'Пречекорување од 30 до 50 km/h над дозволеното: 300 EUR и забрана за управување од 3 до 12 месеци.',
      en: 'Speeding 30 to 50 km/h over the limit: EUR 300 and a driving ban from 3 to 12 months.',
      sr: 'Прекорачење од 30 до 50 km/h изнад ограничења: 300 EUR и забрана управљања од 3 до 12 месеци.',
    },
  }),
  priced({
    code: 'SC-9E2C4F6A1B3D',
    refId: 'SC-2026-051881',
    kind: 'red_light',
    status: 'unpaid',
    plate: 'OH 3318 KT',
    vehicleMake: 'Toyota Yaris',
    carColor: 'white',
    dateTime: '2026-05-15T17:44:00',
    street: { mk: 'Кеј Маршал Тито', en: 'Marshal Tito Quay', sr: 'Кеј Маршал Тито' },
    city: { mk: 'Охрид', en: 'Ohrid', sr: 'Охрид' },
    coordinates: { lat: 41.11731, lng: 20.80198 },
    cameraId: 'CAM-OH-003',
    issuedAt: '2026-05-15T18:09:00',
    baseFineEUR: 250,
    drivingBan: {
      mk: 'Забрана за управување од 3 до 12 месеци.',
      en: 'Driving ban from 3 to 12 months.',
      sr: 'Забрана управљања од 3 до 12 месеци.',
    },
    legalNote: {
      mk: 'Минување на црвено светло: 250 EUR и забрана за управување од 3 до 12 месеци.',
      en: 'Running a red light: EUR 250 and a driving ban from 3 to 12 months.',
      sr: 'Пролазак кроз црвено светло: 250 EUR и забрана управљања од 3 до 12 месеци.',
    },
  }),
  priced({
    code: 'SC-1A4E7C2B9F5D',
    refId: 'SC-2026-051862',
    kind: 'no_parking',
    status: 'unpaid',
    plate: 'BT 2207 OP',
    vehicleMake: 'Opel Astra',
    carColor: 'silver',
    dateTime: '2026-05-15T14:12:00',
    street: { mk: 'Ул. Цар Самоил', en: 'Tsar Samoil St.', sr: 'Улица Цар Самоил' },
    city: { mk: 'Битола', en: 'Bitola', sr: 'Битола' },
    coordinates: { lat: 41.03412, lng: 21.34011 },
    cameraId: 'CAM-BT-005',
    issuedAt: '2026-05-15T14:33:00',
    baseFineEUR: 50,
    parkingSeverity: 'disabled_space',
    legalNote: {
      mk: 'Паркирање на место наменето за лица со попреченост: 50 EUR. Можно е подигнување со пајак-служба со дополнителни трошоци.',
      en: 'Parking in a space reserved for persons with disabilities: EUR 50. Towing may apply with additional costs.',
      sr: 'Паркирање на месту намењеном особама са инвалидитетом: 50 EUR. Могуће је одношење паук-службом уз додатне трошкове.',
    },
  }),

  priced({
    code: 'SC-8B5F3D1C7A4E',
    refId: 'SC-2026-050331',
    kind: 'red_light',
    status: 'unpaid',
    plate: 'SK 7042 BC',
    vehicleMake: 'Volkswagen Golf',
    carColor: 'silver',
    dateTime: '2026-05-10T08:15:00',
    street: { mk: 'Ул. Партизанска', en: 'Partizanska St.', sr: 'Улица Партизанска' },
    city: { mk: 'Скопје', en: 'Skopje', sr: 'Скопље' },
    coordinates: { lat: 41.99813, lng: 21.42544 },
    cameraId: 'CAM-SK-014',
    issuedAt: '2026-05-10T08:38:00',
    baseFineEUR: 250,
    drivingBan: {
      mk: 'Забрана за управување од 3 до 12 месеци.',
      en: 'Driving ban from 3 to 12 months.',
      sr: 'Забрана управљања од 3 до 12 месеци.',
    },
    legalNote: {
      mk: 'Минување на црвено светло: 250 EUR и забрана за управување од 3 до 12 месеци.',
      en: 'Running a red light: EUR 250 and a driving ban from 3 to 12 months.',
      sr: 'Пролазак кроз црвено светло: 250 EUR и забрана управљања од 3 до 12 месеци.',
    },
  }),
  priced({
    code: 'SC-3D9A2F7B4C1E',
    refId: 'SC-2026-050112',
    kind: 'expired_registration',
    status: 'unpaid',
    plate: 'TT 1092 VM',
    vehicleMake: 'Renault Clio',
    carColor: 'blue',
    dateTime: '2026-05-10T10:30:00',
    street: { mk: 'Бул. Илинден', en: 'Ilinden Blvd.', sr: 'Булевар Илинден' },
    city: { mk: 'Тетово', en: 'Tetovo', sr: 'Тетово' },
    coordinates: { lat: 41.99971, lng: 20.97169 },
    cameraId: 'CAM-TT-004',
    issuedAt: '2026-05-10T10:55:00',
    baseFineEUR: 100,
    ownerFineEUR: 250,
    legalNote: {
      mk: 'Истечена регистрација или сообраќајна дозвола: 100 EUR за возачот; 250 EUR за сопственикот ако е друго лице.',
      en: 'Expired registration or traffic permit: EUR 100 for the driver; EUR 250 for the owner if different.',
      sr: 'Истекла регистрација или саобраћајна дозвола: 100 EUR за возача; 250 EUR за власника ако је друго лице.',
    },
  }),

  // PAID
  priced({
    code: 'SC-5C8E1A3B6F2D',
    refId: 'SC-2026-050268',
    kind: 'no_parking',
    status: 'paid',
    plate: 'KM 7723 BG',
    vehicleMake: 'Skoda Octavia',
    carColor: 'red',
    dateTime: '2026-05-09T15:30:00',
    street: { mk: 'Ул. Индустриска', en: 'Industrial St.', sr: 'Улица Индустријска' },
    city: { mk: 'Куманово', en: 'Kumanovo', sr: 'Куманово' },
    coordinates: { lat: 42.13281, lng: 21.71432 },
    cameraId: 'CAM-KM-007',
    issuedAt: '2026-05-09T15:55:00',
    baseFineEUR: 30,
    parkingSeverity: 'standard',
    legalNote: {
      mk: 'Стандардно непрописно запирање или паркирање: 30 EUR.',
      en: 'Standard illegal stopping or parking: EUR 30.',
      sr: 'Стандардно непрописно заустављање или паркирање: 30 EUR.',
    },
  }),

  // VOIDED
  priced({
    code: 'SC-4F1A8B2D5E9C',
    refId: 'SC-2026-049011',
    kind: 'speeding',
    status: 'voided',
    plate: 'VL 3305 PA',
    vehicleMake: 'Hyundai Tucson',
    carColor: 'blue',
    dateTime: '2026-04-30T07:50:00',
    street: { mk: 'Автопат Б1 (Велес—Скопје)', en: 'A1 Motorway (Veles—Skopje)', sr: 'Аутопут Б1 (Велес—Скопље)' },
    city: { mk: 'Велес', en: 'Veles', sr: 'Велес' },
    coordinates: { lat: 41.71163, lng: 21.77441 },
    speedRecorded: 72,
    speedLimit: 50,
    cameraId: 'CAM-VL-009',
    issuedAt: '2026-04-30T08:15:00',
    baseFineEUR: 45,
    legalNote: {
      mk: 'Пречекорување од 20 до 30 km/h над дозволеното: 45 EUR.',
      en: 'Speeding 20 to 30 km/h over the limit: EUR 45.',
      sr: 'Прекорачење од 20 до 30 km/h изнад ограничења: 45 EUR.',
    },
  }),

  // APPEAL PENDING
  priced({
    code: 'SC-9A3B8C1D4F2E',
    refId: 'SC-2026-051518',
    kind: 'speeding',
    status: 'appeal_pending',
    plate: 'BT 4418 RD',
    vehicleMake: 'Ford Focus',
    carColor: 'red',
    dateTime: '2026-05-05T10:35:00',
    street: { mk: 'Бул. 1 Мај', en: '1st of May Blvd.', sr: 'Булевар 1. мај' },
    city: { mk: 'Битола', en: 'Bitola', sr: 'Битола' },
    coordinates: { lat: 41.02972, lng: 21.33653 },
    speedRecorded: 94,
    speedLimit: 50,
    cameraId: 'CAM-BT-011',
    issuedAt: '2026-05-05T10:58:00',
    baseFineEUR: 300,
    drivingBan: {
      mk: 'Забрана за управување од 3 до 12 месеци.',
      en: 'Driving ban from 3 to 12 months.',
      sr: 'Забрана управљања од 3 до 12 месеци.',
    },
    legalNote: {
      mk: 'Пречекорување од 30 до 50 km/h над дозволеното: 300 EUR и забрана за управување од 3 до 12 месеци.',
      en: 'Speeding 30 to 50 km/h over the limit: EUR 300 and a driving ban from 3 to 12 months.',
      sr: 'Прекорачење од 30 до 50 km/h изнад ограничења: 300 EUR и забрана управљања од 3 до 12 месеци.',
    },
  }),
];
